# Generated by Django 5.2.12 on 2026-03-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectapplication',
            unique_together={('project', 'freelancer')},
        ),
    ]
